# .github/workflows/deploy.yml

name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deployment to ec2

    steps:
      - name: Debug EC2 host
        run: echo "Deploying to ${{ secrets.EC2_HOST }}"
      - name: SSH deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Connected to host: $(hostname -I)"
            set -e
            cd /var/www/nextmark-backend
            echo "Resetting repo..."
            git fetch origin
            git reset --hard origin/main

            source venv/bin/activate
            pip install -r requirements.txt

            set -a
            source /home/ubuntu/config/nextmark/.env
            set +a

            export FLASK_APP=cli:app
            flask db upgrade

            sudo systemctl restart nextmark-*
            sleep 3
            response=$(curl -s http://localhost:5050/)
            echo "$response"
            echo "$response" | grep '"status":"ok"' || exit 1

            echo "Performing external health check for ssl domain deliveryapi.beyoworkaroundtheclock ...."
            curl -f https://deliveryapi.beyoworkaroundtheclock.com || exit 1